# Generated by Django 3.2.4 on 2021-07-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping_list.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_list.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_list.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Product Name')),
                ('category', models.ForeignKey(blank=True, help_text='This should indicate a type of product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping_list.category')),
                ('storage', models.ForeignKey(blank=True, help_text='The location in which this product should be stored. Used in recipe ingredient lists.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping_list.storage')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, choices=[('', 'items'), ('g', 'grams'), ('ml', 'millilitres'), ('pts', 'pints'), ('tsp', 'teaspoons'), ('tbsp', 'tablespoons'), ('kg', 'kilograms'), ('l', 'litres')], default='')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping_list.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_list.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_list.recipe')),
            ],
        ),
    ]
