# Generated by Django 3.2.4 on 2021-07-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.TextField(blank=True, choices=[('', 'items'), ('g', 'grams'), ('ml', 'millilitres'), ('pts', 'pints'), ('tsp', 'teaspoons'), ('tbsp', 'tablespoons'), ('kg', 'kilograms'), ('l', 'litres'), ('pack', 'pack'), ('cloves', 'cloves'), ('handfuls', 'handfuls')], default=''),
        ),
    ]
