# Generated by Django 4.0.3 on 2022-09-13 10:47

from django.db import migrations, models
import shopping_list.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sorting_weight',
            field=models.IntegerField(default=shopping_list.models.Category.sorting_weight_default),
        ),
    ]
