# Generated by Django 4.0.3 on 2022-09-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_category_sorting_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sorting_weight',
        ),
    ]
