# Generated by Django 4.0.3 on 2022-09-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_category_sorting_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pluralised_name',
            field=models.CharField(default='', max_length=80, verbose_name='Pluralised Product Name'),
            preserve_default=False,
        ),
    ]
