# Generated by Django 3.2.4 on 2021-07-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_auto_20210729_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_unit',
            field=models.TextField(blank=True, choices=[('', 'item'), ('g', 'gram'), ('ml', 'millilitre'), ('pt', 'pint'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('kg', 'kilogram'), ('l', 'litre'), ('pack', 'pack'), ('clove', 'clove'), ('handful', 'handful')], default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='pluralised',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.TextField(blank=True, choices=[('', 'item'), ('g', 'gram'), ('ml', 'millilitre'), ('pt', 'pint'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('kg', 'kilogram'), ('l', 'litre'), ('pack', 'pack'), ('clove', 'clove'), ('handful', 'handful')], default=''),
        ),
    ]
