# Generated by Django 4.0.3 on 2023-03-07 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_alter_product_pluralised_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
