# Generated by Django 4.0.2 on 2022-02-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0004_auto_20210801_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='default_unit',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
