# Generated by Django 4.0.2 on 2022-02-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0005_remove_ingredient_unit_remove_product_default_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.TextField(blank=True, default='', max_length=40, null=True),
        ),
    ]
