# Generated by Django 4.0.2 on 2022-02-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0007_ingredient_on_shopping_list_alter_ingredient_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='storage',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
