# Generated by Django 4.0.2 on 2022-02-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0008_remove_product_storage_delete_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pluralised',
        ),
        migrations.AddField(
            model_name='product',
            name='pluralised_name',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Pluralised Product Name'),
        ),
    ]
