# Generated by Django 4.0.2 on 2022-02-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0009_remove_product_pluralised_product_pluralised_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
